plugins {
    id 'java'
    id 'jigsaw-cosmic-reach'
}

group = p_group
version = p_version

jigsawGame {
    splitSourceSets()
}
jigsawAccess {
    addManipulators(file("$projectDir/src/common/resources/${p_id}.manipulator"))
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    puzzleLoader "dev.puzzleshq:puzzle-loader-core:$puzzle_loader_core_version"
    puzzleLoader "dev.puzzleshq:puzzle-loader-cosmic:$puzzle_loader_cosmic_version"

    cosmicReach("finalforeach:cosmic-reach:${cosmic_reach_version}")
}

processCommonResources {

    def authors = "\"" + p_author + "\""

    if (p_author.contains(",")) {
        def items = p_author.split(',')
        StringBuilder sb = new StringBuilder()

        def isFirst = true

        for (item in items) {
            if (!isFirst) sb.append(", ")
            sb.append("\"" + item + "\"")
            isFirst = false
        }

        authors = sb.toString()
    }

    def projectProperties = [
            "p_name": p_name,
            "p_version": ((String)version).contains(".") ? version : "0.0.0",
            "p_desc": p_desc,

            "p_id": p_id,
            "p_group": p_group,
            "p_authors": authors
    ]

    inputs.properties projectProperties

    filesMatching(["puzzle.mod.json"]) {
        expand projectProperties
    }
}

wrapper {
    gradleVersion = "8.14"
    distributionType = Wrapper.DistributionType.ALL
}