# Project Details
p_name = Simply Zooming
p_id = simply_zooming
p_group = io.github.spicylemon2623
p_desc = A simple zoom mod
p_author = Spicylemon
p_version= 0.8.3

# Cosmic Reach
cosmic_reach_version = 0.5.26-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.3-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta